version: '3'
services:
  dev:
    build: ./dev-container
    working_dir: /app
    volumes:
      - ./:/app
    command: echo "start cli by running docker-compose run dev bash"
  ganache:
    image: trufflesuite/ganache-cli:v6.9.0
    ports:
      - 8545:8545
    command: ganache-cli --networkId 50 --accounts 20 -l 19000000 -e 10000000000 -m 'concert load couple harbor equip island argue ramp clarify fence smart topic'
