name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-2"
  CLUSTER_NAME: dev
  AWS_ACCOUNT_ID: ${{ secrets.NONPROD_AWS_ACCOUNT_ID }}
  ROLE_ARN: ${{ secrets.NONPROD_ROLE_ARN }}
  APP_NAME: contracts
  ECR_REPOSITORY: platform-contracts
  CONTAINER_PORT: "4000"
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  BUILD_VERSION: ${{ github.sha }}
  DEPLOY_TIMEOUT: "600"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true
