name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0
        
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Bootstrap packages
      run: yarn lerna bootstrap

    - name: Setup repos
      run: yarn setup

    - name: Run linter
      run: yarn lint

    - name: Docker Compose Logs
      run: docker-compose logs

    - name: Docker Compose PS
      run: docker-compose ps

    - name: Run tests
      run: yarn test
      env:
        ETHERSCAN_KEY: 0
        RPC_ENDPOINT: http://localhost:8445
        DEPLOYMENT_NETWORK_ID: 50
        DEPLOYMENT_ENVIRONMENT: development
