name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0

    - name: Install dependencies
      run: yarn install
    
    - name: Bootstrap packages
      run: yarn lerna bootstrap

    - name: Setup repos
      run: yarn setup
      env: 
        ETHERSCAN_KEY: 0

    - name: Run linter
      run: yarn lint

    - name: Run tests
      run: yarn test
