name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup node
    - uses: actions/checkout@v1
    
    - name: Setup node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0

    - name: Install dependencies
      run: yarn install

    - name: Clear development addresses
      run: node ./scripts/clearDevAddresses.js
